import bcrypt from 'bcryptjs';
import { User, Category, Brand, Product, Coupon, Order, Review } from './types.ts';

// Password hashes:
// Admin@123 -> $2a$10$7Z2v...
// User@123 -> $2a$10$w...
const adminHash = bcrypt.hashSync('Admin@123', 10);
const userHash = bcrypt.hashSync('User@123', 10);

export const initialUsers: User[] = [
  {
    id: 'user-admin-1',
    email: 'admin@techzone.vn',
    password: adminHash,
    fullName: 'Quản Trị Viên TechZone',
    phone: '0901234567',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'ADMIN',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'user-customer-1',
    email: 'user@techzone.vn',
    password: userHash,
    fullName: 'Nguyễn Văn Minh',
    phone: '0987654321',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    role: 'USER',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const initialCategories: Category[] = [
  { id: 'cat-cpu', name: 'CPU - Bộ Vi Xử Lý', slug: 'cpu', icon: 'Cpu', image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&auto=format&fit=crop&q=80', description: 'Intel Core & AMD Ryzen thế hệ mới nhất cho Gaming & Đồ họa' },
  { id: 'cat-gpu', name: 'VGA - Card Màn Hình', slug: 'gpu', icon: 'Layers', image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=600&auto=format&fit=crop&q=80', description: 'NVIDIA GeForce RTX 40 & 50 Series, AMD Radeon RX hiệu năng đỉnh' },
  { id: 'cat-mainboard', name: 'Mainboard - Bo Mạch Chủ', slug: 'mainboard', icon: 'Grid', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80', description: 'Bo mạch chủ chipset Z790, B760, X670E, B650 cao cấp' },
  { id: 'cat-ram', name: 'RAM - Bộ Nhớ Trong', slug: 'ram', icon: 'HardDrive', image: 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=600&auto=format&fit=crop&q=80', description: 'RAM DDR5 và DDR4 RGB tốc độ bus cao' },
  { id: 'cat-ssd', name: 'SSD - Ổ Cứng Thể Rắn', slug: 'ssd', icon: 'Database', image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&auto=format&fit=crop&q=80', description: 'SSD M.2 NVMe PCIe Gen4/Gen5 tốc độ đọc ghi vượt trội' },
  { id: 'cat-psu', name: 'Nguồn Máy Tính (PSU)', slug: 'psu', icon: 'Zap', image: 'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=600&auto=format&fit=crop&q=80', description: 'Chuẩn 80 Plus Gold, Platinum công suất từ 650W đến 1300W' },
  { id: 'cat-case', name: 'Vỏ Case Máy Tính', slug: 'case', icon: 'Box', image: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=600&auto=format&fit=crop&q=80', description: 'Vỏ case bể cá, kính cường lực, airflow tối ưu tản nhiệt' },
  { id: 'cat-cooler', name: 'Tản Nhiệt CPU', slug: 'cooler', icon: 'Fan', image: 'https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=600&auto=format&fit=crop&q=80', description: 'Tản nhiệt nước AIO 240/360mm và tản nhiệt khí tháp đôi' },
  { id: 'cat-monitor', name: 'Màn Hình Máy Tính', slug: 'monitor', icon: 'Monitor', image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80', description: 'Màn hình Gaming 144Hz - 240Hz, 2K, 4K OLED, IPS' },
  { id: 'cat-gear', name: 'Bàn Phím & Chuột Gaming', slug: 'gear', icon: 'MousePointer', image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&auto=format&fit=crop&q=80', description: 'Bàn phím cơ Custom, chuột quang không dây siêu nhẹ' },
  { id: 'cat-audio', name: 'Tai Nghe & Loa', slug: 'audio', icon: 'Headphones', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80', description: 'Tai nghe gaming vòm 7.1, mic chống ồn chất âm chân thực' },
  { id: 'cat-accessories', name: 'Cáp & Phụ Kiện PC', slug: 'accessories', icon: 'Cable', image: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=600&auto=format&fit=crop&q=80', description: 'Cáp HDMI 2.1, DisplayPort 1.4, Hub USB Type-C đa năng' }
];

export const initialBrands: Brand[] = [
  { id: 'brand-intel', name: 'Intel', slug: 'intel', logo: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=200&auto=format&fit=crop&q=80', description: 'Thương hiệu vi xử lý hàng đầu thế giới' },
  { id: 'brand-amd', name: 'AMD', slug: 'amd', logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=200&auto=format&fit=crop&q=80', description: 'Vi xử lý Ryzen & card đồ họa Radeon' },
  { id: 'brand-nvidia', name: 'NVIDIA', slug: 'nvidia', logo: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=200&auto=format&fit=crop&q=80', description: 'Công nghệ đồ họa GeForce RTX và trí tuệ nhân tạo' },
  { id: 'brand-asus', name: 'ASUS ROG', slug: 'asus', logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&auto=format&fit=crop&q=80', description: 'Republic of Gamers - Đỉnh cao gaming gear và phần cứng' },
  { id: 'brand-msi', name: 'MSI', slug: 'msi', logo: 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=200&auto=format&fit=crop&q=80', description: 'Phần cứng gaming chuyên nghiệp hàng đầu' },
  { id: 'brand-gigabyte', name: 'Gigabyte AORUS', slug: 'gigabyte', logo: 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=200&auto=format&fit=crop&q=80', description: 'Bo mạch chủ và VGA gaming chất lượng cao' },
  { id: 'brand-corsair', name: 'Corsair', slug: 'corsair', logo: 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=200&auto=format&fit=crop&q=80', description: 'Bộ nhớ RAM, tản nhiệt và nguồn máy tính uy tín' },
  { id: 'brand-kingston', name: 'Kingston', slug: 'kingston', logo: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=200&auto=format&fit=crop&q=80', description: 'Giải pháp lưu trữ SSD và bộ nhớ RAM Fury' },
  { id: 'brand-samsung', name: 'Samsung', slug: 'samsung', logo: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=200&auto=format&fit=crop&q=80', description: 'SSD NVMe và màn hình công nghệ cao' },
  { id: 'brand-logitech', name: 'Logitech G', slug: 'logitech', logo: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=200&auto=format&fit=crop&q=80', description: 'Gaming gear không dây Lightspeed số 1 thế giới' },
  { id: 'brand-razer', name: 'Razer', slug: 'razer', logo: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=200&auto=format&fit=crop&q=80', description: 'For Gamers. By Gamers.' },
  { id: 'brand-deepcool', name: 'DeepCool', slug: 'deepcool', logo: 'https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=200&auto=format&fit=crop&q=80', description: 'Tản nhiệt khí, nước và case tản nhiệt thông minh' }
];

export const initialProducts: Product[] = [
  // ===================== CPU =====================
  {
    id: 'prod-cpu-1',
    name: 'CPU AMD Ryzen 7 7800X3D (4.2GHz Boost 5.0GHz, 8 Nhân 16 Luồng, 104MB Cache, AM5)',
    slug: 'amd-ryzen-7-7800x3d',
    sku: 'CPU-AMD-7800X3D',
    description: 'CPU chơi game mạnh nhất thế giới với công nghệ 3D V-Cache độc quyền từ AMD. Tối ưu khung hình FPS mượt mà cho mọi tựa game AAA và Esports.',
    price: 10490000,
    oldPrice: 11990000,
    discount: 13,
    stock: 25,
    soldCount: 88,
    images: [
      'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.9,
    reviewCount: 42,
    isFeatured: true,
    isFlashSale: true,
    categoryId: 'cat-cpu',
    categorySlug: 'cpu',
    brandId: 'brand-amd',
    brandName: 'AMD',
    socket: 'AM5',
    ramType: 'DDR5',
    wattage: 120,
    specifications: {
      'Số nhân / luồng': '8 nhân / 16 luồng',
      'Xung nhịp cơ bản': '4.2 GHz',
      'Xung nhịp tối đa': '5.0 GHz',
      'Bộ nhớ đệm L3': '96MB (Tổng 104MB 3D V-Cache)',
      'Socket hỗ trợ': 'AM5',
      'Chuẩn RAM hỗ trợ': 'DDR5 5200MHz',
      'TDP điện năng': '120W',
      'Đồ họa tích hợp': 'AMD Radeon Graphics (RDNA 2)'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cpu-2',
    name: 'CPU Intel Core i7-14700K (Up to 5.6GHz, 20 Nhân 28 Luồng, 33MB Cache, LGA1700)',
    slug: 'intel-core-i7-14700k',
    sku: 'CPU-INT-14700K',
    description: 'Vi xử lý Intel thế hệ thứ 14 Raptor Lake Refresh với 20 nhân mạnh mẽ, cân bằng hoàn hảo giữa hiệu năng chơi game 4K và tác vụ render 3D chuyên sâu.',
    price: 10890000,
    oldPrice: 12200000,
    discount: 11,
    stock: 18,
    soldCount: 65,
    images: [
      'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.8,
    reviewCount: 31,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-cpu',
    categorySlug: 'cpu',
    brandId: 'brand-intel',
    brandName: 'Intel',
    socket: 'LGA1700',
    ramType: 'DDR5',
    wattage: 253,
    specifications: {
      'Số nhân / luồng': '20 nhân (8 P-Core + 12 E-Core) / 28 luồng',
      'Xung nhịp Turbo Boost': 'Lên tới 5.6 GHz',
      'Bộ nhớ đệm Smart Cache': '33MB',
      'Socket': 'LGA1700',
      'Chuẩn RAM hỗ trợ': 'DDR5 5600MHz & DDR4 3200MHz',
      'TDP tối đa': '253W',
      'iGPU': 'Intel UHD Graphics 770'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cpu-3',
    name: 'CPU AMD Ryzen 5 7600 (3.8GHz Boost 5.1GHz, 6 Nhân 12 Luồng, 38MB Cache, AM5)',
    slug: 'amd-ryzen-5-7600',
    sku: 'CPU-AMD-7600',
    description: 'Lựa chọn quốc dân phân khúc tầm trung trên nền tảng socket AM5. Hiệu năng vượt bậc, nhiệt độ mát mẻ kèm quạt tản nhiệt Wraith Stealth zin.',
    price: 5290000,
    oldPrice: 5990000,
    discount: 12,
    stock: 40,
    soldCount: 140,
    images: [
      'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.85,
    reviewCount: 56,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-cpu',
    categorySlug: 'cpu',
    brandId: 'brand-amd',
    brandName: 'AMD',
    socket: 'AM5',
    ramType: 'DDR5',
    wattage: 65,
    specifications: {
      'Số nhân / luồng': '6 nhân / 12 luồng',
      'Xung nhịp tối đa': '5.1 GHz',
      'Cache L3': '32MB',
      'Socket': 'AM5',
      'Chuẩn RAM': 'DDR5',
      'TDP': '65W'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cpu-4',
    name: 'CPU Intel Core i5-14400F (Up to 4.7GHz, 10 Nhân 16 Luồng, 20MB Cache, LGA1700)',
    slug: 'intel-core-i5-14400f',
    sku: 'CPU-INT-14400F',
    description: 'CPU quốc dân cho cấu hình PC Gaming tầm trung. 10 nhân xử lý mượt mọi tác vụ vừa học tập, làm việc vừa livestream chơi game.',
    price: 4990000,
    oldPrice: 5690000,
    discount: 12,
    stock: 35,
    soldCount: 110,
    images: [
      'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.7,
    reviewCount: 38,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-cpu',
    categorySlug: 'cpu',
    brandId: 'brand-intel',
    brandName: 'Intel',
    socket: 'LGA1700',
    ramType: 'DDR5',
    wattage: 65,
    specifications: {
      'Số nhân / luồng': '10 nhân (6 P-Core + 4 E-Core) / 16 luồng',
      'Xung nhịp Max': '4.7 GHz',
      'Cache': '20MB Intel Smart Cache',
      'Socket': 'LGA1700',
      'TDP': '65W - 148W Turbo'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== GPU =====================
  {
    id: 'prod-gpu-1',
    name: 'Card Màn Hình ASUS ROG Strix GeForce RTX 4090 24GB GDDR6X OC Edition',
    slug: 'asus-rog-strix-rtx-4090-24gb',
    sku: 'GPU-ASUS-4090-STRIX',
    description: 'Đỉnh cao đồ họa thế hệ kiến trúc NVIDIA Ada Lovelace. Tản nhiệt buồng hơi Vapor Chamber, khung kim loại nguyên khối, công nghệ DLSS 3.5 và Ray Tracing toàn phần.',
    price: 54990000,
    oldPrice: 59990000,
    discount: 8,
    stock: 8,
    soldCount: 22,
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 5.0,
    reviewCount: 19,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-gpu',
    categorySlug: 'gpu',
    brandId: 'brand-asus',
    brandName: 'ASUS ROG',
    wattage: 450,
    vram: '24GB GDDR6X',
    specifications: {
      'Nhân đồ họa': 'NVIDIA GeForce RTX 4090',
      'Bộ nhớ VRAM': '24GB GDDR6X 384-bit',
      'Xung nhịp OC': '2640 MHz',
      'CUDA Cores': '16384',
      'Chuẩn giao tiếp': 'PCI Express 4.0',
      'Nguồn khuyến nghị': '1000W',
      'Cổng xuất hình': '2x HDMI 2.1a, 3x DisplayPort 1.4a'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-gpu-2',
    name: 'Card Màn Hình MSI GeForce RTX 4070 Ti SUPER 16GB GAMING X SLIM',
    slug: 'msi-geforce-rtx-4070-ti-super-16gb',
    sku: 'GPU-MSI-4070TIS-16G',
    description: 'Chiến mượt mọi tựa game 2K/4K max setting với 16GB VRAM băng thông cao. Thiết kế mỏng gọn tinh tế cùng quạt tản nhiệt TORX FAN 5.0 êm ái.',
    price: 24590000,
    oldPrice: 26990000,
    discount: 9,
    stock: 14,
    soldCount: 45,
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.9,
    reviewCount: 28,
    isFeatured: true,
    isFlashSale: true,
    categoryId: 'cat-gpu',
    categorySlug: 'gpu',
    brandId: 'brand-msi',
    brandName: 'MSI',
    wattage: 285,
    vram: '16GB GDDR6X',
    specifications: {
      'Nhân đồ họa': 'GeForce RTX 4070 Ti SUPER',
      'VRAM': '16GB GDDR6X 256-bit',
      'CUDA Cores': '8448',
      'Xung nhịp': '2670 MHz',
      'Nguồn khuyến nghị': '750W',
      'Kích thước': '307 x 125 x 51 mm'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-gpu-3',
    name: 'Card Màn Hình Gigabyte GeForce RTX 4060 EAGLE OC 8GB GDDR6',
    slug: 'gigabyte-rtx-4060-eagle-oc-8gb',
    sku: 'GPU-GIGA-4060-8G',
    description: 'Card đồ họa quốc dân thế hệ RTX 40 series. Tiết kiệm điện năng tối đa, hỗ trợ công nghệ DLSS 3 Frame Generation tăng gấp đôi khung hình.',
    price: 8490000,
    oldPrice: 9490000,
    discount: 11,
    stock: 30,
    soldCount: 160,
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.8,
    reviewCount: 75,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-gpu',
    categorySlug: 'gpu',
    brandId: 'brand-gigabyte',
    brandName: 'Gigabyte AORUS',
    wattage: 115,
    vram: '8GB GDDR6',
    specifications: {
      'Nhân đồ họa': 'GeForce RTX 4060',
      'VRAM': '8GB GDDR6 128-bit',
      'Hệ thống tản nhiệt': 'WINDFORCE 3 quạt làm mát',
      'Nguồn đề xuất': '450W',
      'Công suất tiêu thụ': '115W'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== MAINBOARD =====================
  {
    id: 'prod-mb-1',
    name: 'Mainboard ASUS ROG MAXIMUS Z790 DARK HERO (LGA1700, ATX, DDR5, Wi-Fi 7)',
    slug: 'asus-rog-maximus-z790-dark-hero',
    sku: 'MB-ASUS-Z790-DARKHERO',
    description: 'Bo mạch chủ đầu bảng dành cho vi xử lý Intel Core Gen 14. Thiết kế dàn phase nguồn 20+1 cực khủng, khe PCIe 5.0 và kết nối Wi-Fi 7 siêu tốc.',
    price: 18990000,
    oldPrice: 20990000,
    discount: 10,
    stock: 12,
    soldCount: 18,
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.95,
    reviewCount: 15,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-mainboard',
    categorySlug: 'mainboard',
    brandId: 'brand-asus',
    brandName: 'ASUS ROG',
    socket: 'LGA1700',
    ramType: 'DDR5',
    formFactor: 'ATX',
    specifications: {
      'Socket CPU': 'LGA1700',
      'Chipset': 'Intel Z790',
      'Hỗ trợ RAM': '4x DDR5 tối đa 192GB (Up to 8000+ MHz OC)',
      'Khe cắm mở rộng': '2x PCIe 5.0 x16, 1x PCIe 4.0 x4',
      'Lưu trữ': '5x M.2 NVMe (1x PCIe 5.0), 4x SATA 6Gb/s',
      'Mạng không dây': 'Wi-Fi 7 + Bluetooth 5.4, LAN 2.5Gb'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mb-2',
    name: 'Mainboard MSI MAG B650 TOMAHAWK WIFI (Socket AM5, ATX, DDR5, PCIe 4.0)',
    slug: 'msi-mag-b650-tomahawk-wifi',
    sku: 'MB-MSI-B650-TOMAHAWK',
    description: 'Bo mạch chủ AM5 bền bỉ số 1 cho game thủ AMD Ryzen 7000 và 9000 series. Dàn tản nhiệt mở rộng Extended Heatsink làm mát VRM tối đa.',
    price: 5690000,
    oldPrice: 6290000,
    discount: 10,
    stock: 28,
    soldCount: 92,
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.8,
    reviewCount: 44,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-mainboard',
    categorySlug: 'mainboard',
    brandId: 'brand-msi',
    brandName: 'MSI',
    socket: 'AM5',
    ramType: 'DDR5',
    formFactor: 'ATX',
    specifications: {
      'Socket CPU': 'AM5 (AMD Ryzen 7000/8000/9000)',
      'Chipset': 'AMD B650',
      'Chuẩn RAM': '4x DDR5 up to 7600+ MHz (EXPO)',
      'Khe M.2': '3x M.2 PCIe 4.0 x4',
      'Kết nối mạng': 'Wi-Fi 6E, LAN 2.5G Realtek'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mb-3',
    name: 'Mainboard Gigabyte B760M AORUS ELITE AX (LGA1700, Micro-ATX, DDR5, Wi-Fi 6E)',
    slug: 'gigabyte-b760m-aorus-elite-ax',
    sku: 'MB-GIGA-B760M-AORUS',
    description: 'Lựa chọn chuẩn mực Micro-ATX nhỏ gọn nhưng đầy đủ tính năng cao cấp cho các dòng chip Intel Gen 12, 13 và 14.',
    price: 4390000,
    oldPrice: 4890000,
    discount: 10,
    stock: 35,
    soldCount: 80,
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.75,
    reviewCount: 36,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-mainboard',
    categorySlug: 'mainboard',
    brandId: 'brand-gigabyte',
    brandName: 'Gigabyte AORUS',
    socket: 'LGA1700',
    ramType: 'DDR5',
    formFactor: 'Micro-ATX',
    specifications: {
      'Socket CPU': 'LGA1700',
      'Kích thước': 'Micro-ATX',
      'Loại RAM': 'DDR5 7600(OC) MHz',
      'Kết nối': 'Wi-Fi 6E, Bluetooth 5.3, 2.5GbE LAN'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== RAM =====================
  {
    id: 'prod-ram-1',
    name: 'RAM Corsair Dominator Titanium RGB 32GB (2x16GB) DDR5 6000MHz White',
    slug: 'corsair-dominator-titanium-rgb-32gb-ddr5-6000mhz',
    sku: 'RAM-COR-DOM-32G-6000',
    description: 'Dòng RAM siêu cao cấp với dải đèn LED Capellix rực rỡ, thanh top bar có thể tháo rời thay thế tùy biến phong cách case trắng.',
    price: 4690000,
    oldPrice: 5290000,
    discount: 11,
    stock: 20,
    soldCount: 50,
    images: [
      'https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.9,
    reviewCount: 22,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-ram',
    categorySlug: 'ram',
    brandId: 'brand-corsair',
    brandName: 'Corsair',
    ramType: 'DDR5',
    specifications: {
      'Dung lượng': '32GB (2 x 16GB kit)',
      'Chuẩn RAM': 'DDR5',
      'Tốc độ Bus': '6000 MHz',
      'Độ trễ Timing': 'CL30-36-36-76',
      'Điện áp': '1.40V',
      'Profile hỗ trợ': 'Intel XMP 3.0 & AMD EXPO'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ram-2',
    name: 'RAM Kingston Fury Beast RGB 32GB (2x16GB) DDR5 5600MHz Black',
    slug: 'kingston-fury-beast-rgb-32gb-ddr5-5600mhz',
    sku: 'RAM-KING-FURY-32G',
    description: 'Hiệu năng DDR5 mạnh mẽ, thiết kế tản nhiệt nhôm đen góc cạnh cùng hiệu ứng RGB mượt mà hỗ trợ đồng bộ mọi hệ thống.',
    price: 2990000,
    oldPrice: 3490000,
    discount: 14,
    stock: 45,
    soldCount: 130,
    images: [
      'https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.8,
    reviewCount: 65,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-ram',
    categorySlug: 'ram',
    brandId: 'brand-kingston',
    brandName: 'Kingston',
    ramType: 'DDR5',
    specifications: {
      'Dung lượng': '32GB (2x16GB)',
      'Tốc độ Bus': '5600 MHz',
      'Chuẩn': 'DDR5',
      'Timing': 'CL36',
      'Đèn LED': 'RGB tùy biến qua Fury CTRL'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ram-3',
    name: 'RAM Corsair Vengeance LPX 16GB (2x8GB) DDR4 3200MHz Black',
    slug: 'corsair-vengeance-lpx-16gb-ddr4-3200mhz',
    sku: 'RAM-COR-VEN-16G-D4',
    description: 'RAM DDR4 cấu hình thấp Low-Profile tương thích tuyệt đối với mọi tản nhiệt khí to lớn, hiệu năng bền bỉ qua năm tháng.',
    price: 990000,
    oldPrice: 1250000,
    discount: 21,
    stock: 60,
    soldCount: 220,
    images: [
      'https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.75,
    reviewCount: 88,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-ram',
    categorySlug: 'ram',
    brandId: 'brand-corsair',
    brandName: 'Corsair',
    ramType: 'DDR4',
    specifications: {
      'Dung lượng': '16GB (2 x 8GB)',
      'Chuẩn': 'DDR4',
      'Bus': '3200 MHz',
      'Timing': 'CL16-20-20-38'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== SSD =====================
  {
    id: 'prod-ssd-1',
    name: 'Ổ Cứng SSD Samsung 990 PRO 2TB PCIe 4.0 NVMe M.2 (Đọc 7450MB/s, Ghi 6900MB/s)',
    slug: 'samsung-990-pro-2tb-nvme-m2',
    sku: 'SSD-SAM-990PRO-2TB',
    description: 'SSD chuẩn NVMe Gen 4 nhanh nhất thế giới. Tốc độ đọc ghi ngẫu nhiên tăng 55% so với 980 Pro, tối ưu hóa cho tác vụ đồ họa và PS5.',
    price: 4890000,
    oldPrice: 5590000,
    discount: 13,
    stock: 25,
    soldCount: 95,
    images: [
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.95,
    reviewCount: 50,
    isFeatured: true,
    isFlashSale: true,
    categoryId: 'cat-ssd',
    categorySlug: 'ssd',
    brandId: 'brand-samsung',
    brandName: 'Samsung',
    storageType: 'NVMe M.2',
    specifications: {
      'Dung lượng': '2TB',
      'Chuẩn giao tiếp': 'PCIe Gen 4.0 x4, NVMe 2.0',
      'Tốc độ đọc tuần tự': 'Lên tới 7,450 MB/s',
      'Tốc độ ghi tuần tự': 'Lên tới 6,900 MB/s',
      'Độ bền TBW': '1200 TBW',
      'Bảo hành': '5 năm chính hãng'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ssd-2',
    name: 'Ổ Cứng SSD Kingston NV2 1TB PCIe 4.0 NVMe M.2 2280',
    slug: 'kingston-nv2-1tb-pcie-4-nvme',
    sku: 'SSD-KING-NV2-1TB',
    description: 'SSD NVMe giá tốt nhất thị trường cho giải pháp lưu trữ tốc độ cao, khởi động Windows và load game chỉ trong tích tắc.',
    price: 1590000,
    oldPrice: 1890000,
    discount: 16,
    stock: 70,
    soldCount: 310,
    images: [
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.7,
    reviewCount: 110,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-ssd',
    categorySlug: 'ssd',
    brandId: 'brand-kingston',
    brandName: 'Kingston',
    storageType: 'NVMe M.2',
    specifications: {
      'Dung lượng': '1TB (1000GB)',
      'Giao diện': 'PCIe 4.0 x4 NVMe',
      'Tốc độ đọc/ghi': '3500 / 2100 MB/s',
      'Kích thước': 'M.2 2280'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== PSU =====================
  {
    id: 'prod-psu-1',
    name: 'Nguồn Máy Tính Corsair RM850e 850W 80 Plus Gold Full Modular ATX 3.0',
    slug: 'corsair-rm850e-850w-80-plus-gold-atx-3-0',
    sku: 'PSU-COR-RM850E',
    description: 'Nguồn chuẩn ATX 3.0 và PCIe 5.0 thế hệ mới trang bị cáp 12VHPWR cho card đồ họa RTX 40 & 50 series, tụ điện chất lượng cao chuẩn quân đội.',
    price: 3390000,
    oldPrice: 3890000,
    discount: 13,
    stock: 22,
    soldCount: 85,
    images: [
      'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.9,
    reviewCount: 34,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-psu',
    categorySlug: 'psu',
    brandId: 'brand-corsair',
    brandName: 'Corsair',
    wattage: 850,
    specifications: {
      'Công suất thực': '850W',
      'Chuẩn hiệu suất': '80 PLUS Gold (lên đến 90%)',
      'Thiết kế cáp': 'Full Modular (rời 100%)',
      'Chuẩn ATX': 'ATX 3.0 kèm cáp PCIe 5.0 12V-2x6',
      'Kích thước quạt': '120mm Rifle Bearing tĩnh lặng'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-psu-2',
    name: 'Nguồn Máy Tính MSI MAG A650BN 650W 80 Plus Bronze',
    slug: 'msi-mag-a650bn-650w-80-plus-bronze',
    sku: 'PSU-MSI-A650BN',
    description: 'Nguồn công suất 650W chuẩn 80 Plus Bronze cho các dàn máy gaming quốc dân sử dụng RTX 4060, RX 7600 hoạt động bền bỉ.',
    price: 1390000,
    oldPrice: 1650000,
    discount: 16,
    stock: 40,
    soldCount: 145,
    images: [
      'https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.8,
    reviewCount: 49,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-psu',
    categorySlug: 'psu',
    brandId: 'brand-msi',
    brandName: 'MSI',
    wattage: 650,
    specifications: {
      'Công suất': '650W',
      'Chứng nhận': '80 PLUS Bronze',
      'Bảo vệ': 'OVP, OCP, OPP, OTP, SCP',
      'Kích thước': '150 x 140 x 86 mm'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== CASE =====================
  {
    id: 'prod-case-1',
    name: 'Vỏ Case Máy Tính NZXT H9 Flow Dual-Chamber Black (Kính Cường Lực Bể Cá Panorama)',
    slug: 'nzxt-h9-flow-dual-chamber-black',
    sku: 'CASE-NZXT-H9-FLOW-BK',
    description: 'Thiết kế buồng đôi Dual-Chamber hiện đại, mặt kính panorama liền mạch khoe trọn linh kiện bên trong, khả năng lắp tối đa 10 quạt 120mm.',
    price: 4390000,
    oldPrice: 4890000,
    discount: 10,
    stock: 15,
    soldCount: 38,
    images: [
      'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.95,
    reviewCount: 20,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-case',
    categorySlug: 'case',
    brandId: 'brand-corsair',
    brandName: 'Corsair',
    formFactor: 'ATX',
    specifications: {
      'Hỗ trợ Mainboard': 'Mini-ITX, Micro-ATX, ATX',
      'Chiều dài GPU tối đa': '435 mm',
      'Chiều cao tản CPU': '165 mm',
      'Hỗ trợ Radiator': 'Lên tới 360mm ở nóc, đáy và hông',
      'Cổng I/O phía trước': '2x USB 3.2 Gen 1 Type-A, 1x USB 3.2 Gen 2 Type-C'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== TẢN NHIỆT =====================
  {
    id: 'prod-cooler-1',
    name: 'Tản Nhiệt Nước AIO DeepCool LT720 360mm ARGB Black',
    slug: 'deepcool-lt720-360mm-argb-black',
    sku: 'COOL-DEEP-LT720-BK',
    description: 'Bơm nước thế hệ thứ 4 công suất cao, mặt pump gương vô cực hình khối đa diện 3D độc quyền, làm mát tối đa cho CPU i7, i9 và Ryzen 9.',
    price: 3290000,
    oldPrice: 3890000,
    discount: 15,
    stock: 25,
    soldCount: 68,
    images: [
      'https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.88,
    reviewCount: 30,
    isFeatured: true,
    isFlashSale: true,
    categoryId: 'cat-cooler',
    categorySlug: 'cooler',
    brandId: 'brand-deepcool',
    brandName: 'DeepCool',
    specifications: {
      'Kích thước Radiator': '402 x 120 x 27 mm (360mm)',
      'Số lượng quạt': '3x 120mm FK120 PWM',
      'Tương thích socket': 'Intel LGA1700/1200/1151 & AMD AM5/AM4',
      'Tốc độ quạt': '500~2250 RPM',
      'Độ ồn tối đa': '32.9 dB(A)'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cooler-2',
    name: 'Tản Nhiệt Khí CPU Thermalright Peerless Assassin 120 SE ARGB',
    slug: 'thermalright-peerless-assassin-120-se-argb',
    sku: 'COOL-THERMAL-PA120',
    description: 'Ông vua tản khí tháp đôi 6 ống đồng dẫn nhiệt mạ niken, tản nhiệt hiệu năng ngang ngửa tản nước AIO 240mm với mức giá siêu mềm.',
    price: 890000,
    oldPrice: 1100000,
    discount: 19,
    stock: 50,
    soldCount: 190,
    images: [
      'https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.92,
    reviewCount: 82,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-cooler',
    categorySlug: 'cooler',
    brandId: 'brand-deepcool',
    brandName: 'DeepCool',
    specifications: {
      'Loại tản': 'Tháp đôi (Dual Tower)',
      'Ống dẫn nhiệt': '6x 6mm Heatpipes đồng nguyên chất',
      'Hỗ trợ Socket': 'Intel LGA 1700/1200, AMD AM5/AM4',
      'Quạt': '2x TL-C12C-S PWM 120mm RGB'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== MÀN HÌNH =====================
  {
    id: 'prod-mon-1',
    name: 'Màn Hình Gaming ASUS ROG Swift OLED PG27AQDM 27 inch 2K 240Hz 0.03ms',
    slug: 'asus-rog-swift-oled-pg27aqdm-27-inch-2k-240hz',
    sku: 'MON-ASUS-PG27AQDM',
    description: 'Tấm nền OLED cao cấp thế hệ mới tái hiện màu đen sâu thẳm, tần số quét 240Hz thời gian phản hồi 0.03ms siêu nhanh, độ phủ màu 99% DCI-P3.',
    price: 21990000,
    oldPrice: 24990000,
    discount: 12,
    stock: 10,
    soldCount: 26,
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 5.0,
    reviewCount: 18,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-monitor',
    categorySlug: 'monitor',
    brandId: 'brand-asus',
    brandName: 'ASUS ROG',
    specifications: {
      'Kích thước màn hình': '26.5 inch',
      'Độ phân giải': 'QHD 2K (2560 x 1440)',
      'Tấm nền': 'OLED Anti-Glare',
      'Tần số quét': '240 Hz',
      'Thời gian phản hồi': '0.03 ms (GTG)',
      'Công nghệ': 'G-SYNC Compatible, HDR10'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mon-2',
    name: 'Màn Hình Gaming Samsung Odyssey G5 G55C 32 inch 2K Cong 165Hz 1ms',
    slug: 'samsung-odyssey-g5-32-inch-2k-165hz',
    sku: 'MON-SAM-ODYSSEY-G5',
    description: 'Độ cong 1000R hoàn hảo ôm trọn tầm mắt người chơi, độ phân giải 2K sắc nét và tần số 165Hz cho trải nghiệm đắm chìm mọi trận chiến.',
    price: 6490000,
    oldPrice: 7690000,
    discount: 16,
    stock: 20,
    soldCount: 75,
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.78,
    reviewCount: 39,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-monitor',
    categorySlug: 'monitor',
    brandId: 'brand-samsung',
    brandName: 'Samsung',
    specifications: {
      'Kích thước': '32 inch',
      'Độ cong': '1000R Curved',
      'Độ phân giải': '2K WQHD (2560 x 1440)',
      'Tần số quét': '165Hz',
      'Thời gian đáp ứng': '1ms (MPRT)'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== GEAR (BÀN PHÍM, CHUỘT) =====================
  {
    id: 'prod-gear-1',
    name: 'Chuột Gaming Không Dây Logitech G Pro X Superlight 2 Wireless Black',
    slug: 'logitech-g-pro-x-superlight-2-wireless',
    sku: 'MOU-LOGI-GPX2-BK',
    description: 'Huyền thoại chuột esports thế hệ 2 với trọng lượng chỉ 60g, cảm biến HERO 2 32.000 DPI, switch cơ lai quang học LIGHTFORCE siêu nhạy.',
    price: 3690000,
    oldPrice: 4290000,
    discount: 14,
    stock: 35,
    soldCount: 140,
    images: [
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.95,
    reviewCount: 78,
    isFeatured: true,
    isFlashSale: true,
    categoryId: 'cat-gear',
    categorySlug: 'gear',
    brandId: 'brand-logitech',
    brandName: 'Logitech G',
    specifications: {
      'Trọng lượng': '60 gram',
      'Cảm biến': 'HERO 2 32,000 DPI',
      'Switch nút bấm': 'LIGHTFORCE Hybrid Optical-Mechanical',
      'Thời lượng pin': 'Lên đến 95 giờ liên tục',
      'Kết nối': 'LIGHTSPEED Wireless 2000Hz Polling rate'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-gear-2',
    name: 'Bàn Phím Cơ Không Dây Razer BlackWidow V4 Pro Mechanical Gaming Keyboard',
    slug: 'razer-blackwidow-v4-pro-mechanical-keyboard',
    sku: 'KB-RAZ-BWV4-PRO',
    description: 'Bàn phím cơ đỉnh cao với núm xoay đa năng Razer Command Dial, 8 phím macro chuyên dụng, đệm kê tay giả da êm ái cùng hệ thống LED gầm rực rỡ.',
    price: 5490000,
    oldPrice: 6290000,
    discount: 13,
    stock: 18,
    soldCount: 42,
    images: [
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.88,
    reviewCount: 25,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-gear',
    categorySlug: 'gear',
    brandId: 'brand-razer',
    brandName: 'Razer',
    specifications: {
      'Switch': 'Razer Green Mechanical Switches (Clicky)',
      'Polling Rate': '8000 Hz HyperPolling',
      'Keycap': 'Doubleshot ABS chống mờ chữ',
      'Đèn nền': 'Razer Chroma RGB per-key'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== AUDIO =====================
  {
    id: 'prod-audio-1',
    name: 'Tai Nghe Gaming Không Dây Razer BlackShark V2 Pro 2023 White Edition',
    slug: 'razer-blackshark-v2-pro-2023-white',
    sku: 'HS-RAZ-BSV2P-WH',
    description: 'Microphone Razer HyperClear Super Wideband chất lượng studio podcast, màng loa TriForce Titanium 50mm, âm thanh THX Spatial Audio định vị chuẩn xác.',
    price: 4990000,
    oldPrice: 5690000,
    discount: 12,
    stock: 24,
    soldCount: 58,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.9,
    reviewCount: 35,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-audio',
    categorySlug: 'audio',
    brandId: 'brand-razer',
    brandName: 'Razer',
    specifications: {
      'Củ loa': 'Razer TriForce Titanium 50mm',
      'Microphone': 'Razer HyperClear Super Wideband có thể tháo rời',
      'Thời lượng pin': 'Lên tới 70 giờ',
      'Kết nối': 'Không dây 2.4GHz Type-C & Bluetooth 5.2'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ===================== CÁP & PHỤ KIỆN =====================
  {
    id: 'prod-acc-1',
    name: 'Cáp Màn Hình Ugreen DisplayPort 1.4 8K 60Hz / 4K 144Hz Bện Dù Cao Cấp 2M',
    slug: 'cap-displayport-1-4-ugreen-8k-2m',
    sku: 'ACC-UG-DP14-2M',
    description: 'Băng thông 32.4Gbps truyền tải hình ảnh 8K HDR không nén, đầu mạ vàng 24K chống nhiễu tuyệt đối, vỏ bọc dù siêu bền bỉ.',
    price: 350000,
    oldPrice: 450000,
    discount: 22,
    stock: 90,
    soldCount: 340,
    images: [
      'https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.92,
    reviewCount: 140,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-accessories',
    categorySlug: 'accessories',
    brandId: 'brand-kingston',
    brandName: 'Kingston',
    specifications: {
      'Chuẩn kết nối': 'DisplayPort 1.4',
      'Độ phân giải tối đa': '8K@60Hz, 4K@144Hz, 2K@240Hz',
      'Băng thông': '32.4 Gbps',
      'Chiều dài': '2 mét'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-acc-2',
    name: 'Hub Chuyển Đổi Đa Năng Baseus Metal Gleam 8 trong 1 Type-C 100W 4K HDMI',
    slug: 'hub-type-c-baseus-metal-gleam-8-in-1',
    sku: 'ACC-BAS-HUB-8IN1',
    description: 'Tích hợp cổng HDMI 4K, 3x USB 3.0, khe đọc thẻ SD/TF, cổng mạng LAN RJ45 Gigabit và sạc nhanh Type-C Power Delivery 100W.',
    price: 850000,
    oldPrice: 1100000,
    discount: 23,
    stock: 55,
    soldCount: 210,
    images: [
      'https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=800&auto=format&fit=crop&q=80'
    ],
    rating: 4.8,
    reviewCount: 95,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-accessories',
    categorySlug: 'accessories',
    brandId: 'brand-kingston',
    brandName: 'Kingston',
    specifications: {
      'Đầu vào': 'USB Type-C',
      'Cổng mở rộng': '1x HDMI 4K@60Hz, 3x USB 3.0 (5Gbps), 1x RJ45 1000Mbps, 1x PD 100W, SD/TF',
      'Chất liệu': 'Hợp kim nhôm tản nhiệt nguyên khối'
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // Additional 30+ items to reach >50
  {
    id: 'prod-cpu-5',
    name: 'CPU Intel Core i9-14900K (Up to 6.0GHz, 24 Nhân 32 Luồng, 36MB Cache, LGA1700)',
    slug: 'intel-core-i9-14900k',
    sku: 'CPU-INT-14900K',
    description: 'Vi xử lý thương mại mạnh nhất của Intel với xung nhịp chạm ngưỡng 6.0GHz ngay khi xuất xưởng.',
    price: 15490000,
    oldPrice: 16990000,
    discount: 9,
    stock: 15,
    soldCount: 38,
    images: ['https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80'],
    rating: 4.9,
    reviewCount: 29,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-cpu',
    categorySlug: 'cpu',
    brandId: 'brand-intel',
    brandName: 'Intel',
    socket: 'LGA1700',
    ramType: 'DDR5',
    wattage: 253,
    specifications: { 'Số nhân': '24 nhân', 'Xung max': '6.0 GHz', 'Socket': 'LGA1700', 'TDP': '253W' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cpu-6',
    name: 'CPU AMD Ryzen 9 7950X (4.5GHz Boost 5.7GHz, 16 Nhân 32 Luồng, 80MB Cache, AM5)',
    slug: 'amd-ryzen-9-7950x',
    sku: 'CPU-AMD-7950X',
    description: 'Cỗ máy đa nhiệm khổng lồ cho dựng phim 8K, lập trình render và mô phỏng 3D.',
    price: 14290000,
    oldPrice: 15990000,
    discount: 10,
    stock: 12,
    soldCount: 25,
    images: ['https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80'],
    rating: 4.88,
    reviewCount: 22,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-cpu',
    categorySlug: 'cpu',
    brandId: 'brand-amd',
    brandName: 'AMD',
    socket: 'AM5',
    ramType: 'DDR5',
    wattage: 170,
    specifications: { 'Nhân/Luồng': '16N/32L', 'Xung boost': '5.7 GHz', 'Socket': 'AM5', 'TDP': '170W' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cpu-7',
    name: 'CPU Intel Core i3-12100F (3.3GHz Boost 4.3GHz, 4 Nhân 8 Luồng, 12MB Cache, LGA1700)',
    slug: 'intel-core-i3-12100f',
    sku: 'CPU-INT-12100F',
    description: 'Vua phân khúc giá rẻ cho học sinh sinh viên làm việc văn phòng và chơi LOL, FIFA, Valorant mượt mà.',
    price: 1990000,
    oldPrice: 2490000,
    discount: 20,
    stock: 60,
    soldCount: 280,
    images: ['https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80'],
    rating: 4.75,
    reviewCount: 88,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-cpu',
    categorySlug: 'cpu',
    brandId: 'brand-intel',
    brandName: 'Intel',
    socket: 'LGA1700',
    ramType: 'DDR4',
    wattage: 58,
    specifications: { 'Nhân/Luồng': '4N/8L', 'Xung boost': '4.3 GHz', 'Socket': 'LGA1700', 'TDP': '58W' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cpu-8',
    name: 'CPU AMD Ryzen 5 5600 (3.5GHz Boost 4.4GHz, 6 Nhân 12 Luồng, 35MB Cache, AM4)',
    slug: 'amd-ryzen-5-5600',
    sku: 'CPU-AMD-5600',
    description: 'Vi xử lý AM4 quốc dân ngon bổ rẻ nâng cấp dễ dàng cho các hệ thống bo mạch B450 / B550.',
    price: 2690000,
    oldPrice: 3200000,
    discount: 16,
    stock: 45,
    soldCount: 310,
    images: ['https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80'],
    rating: 4.85,
    reviewCount: 104,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-cpu',
    categorySlug: 'cpu',
    brandId: 'brand-amd',
    brandName: 'AMD',
    socket: 'AM4',
    ramType: 'DDR4',
    wattage: 65,
    specifications: { 'Nhân/Luồng': '6N/12L', 'Socket': 'AM4', 'RAM': 'DDR4', 'TDP': '65W' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-gpu-4',
    name: 'Card Màn Hình ASUS ROG Strix GeForce RTX 4080 SUPER 16GB OC Edition',
    slug: 'asus-rog-strix-rtx-4080-super-16gb',
    sku: 'GPU-ASUS-4080S-STRIX',
    description: 'Sức mạnh đồ họa đỉnh cao cận kề 4090 với giá thành tối ưu hơn, khung kim loại phay xước.',
    price: 34990000,
    oldPrice: 38990000,
    discount: 10,
    stock: 9,
    soldCount: 28,
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80'],
    rating: 4.95,
    reviewCount: 16,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-gpu',
    categorySlug: 'gpu',
    brandId: 'brand-asus',
    brandName: 'ASUS ROG',
    wattage: 320,
    vram: '16GB GDDR6X',
    specifications: { 'VRAM': '16GB GDDR6X', 'Cores': '10240 CUDA', 'Nguồn khuyến nghị': '850W' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-gpu-5',
    name: 'Card Màn Hình Gigabyte Radeon RX 7800 XT GAMING OC 16GB GDDR6',
    slug: 'gigabyte-radeon-rx-7800-xt-16gb',
    sku: 'GPU-GIGA-RX7800XT',
    description: 'Đối thủ đáng gờm ở phân khúc 2K Gaming từ AMD, trang bị 16GB bộ nhớ cùng kiến trúc RDNA 3.',
    price: 15490000,
    oldPrice: 17200000,
    discount: 10,
    stock: 18,
    soldCount: 52,
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80'],
    rating: 4.8,
    reviewCount: 33,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-gpu',
    categorySlug: 'gpu',
    brandId: 'brand-amd',
    brandName: 'AMD',
    wattage: 263,
    vram: '16GB GDDR6',
    specifications: { 'VRAM': '16GB GDDR6 256-bit', 'Nguồn đề xuất': '700W' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-gpu-6',
    name: 'Card Màn Hình MSI GeForce RTX 4060 Ti VENTUS 2X BLACK 8G OC',
    slug: 'msi-rtx-4060-ti-ventus-2x-8g',
    sku: 'GPU-MSI-4060TI-8G',
    description: 'Kích thước nhỏ gọn 2 quạt phù hợp mọi vỏ case, hiệu năng mạnh mẽ cân tốt đồ họa Premier, Photoshop.',
    price: 10990000,
    oldPrice: 12490000,
    discount: 12,
    stock: 25,
    soldCount: 98,
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80'],
    rating: 4.82,
    reviewCount: 45,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-gpu',
    categorySlug: 'gpu',
    brandId: 'brand-msi',
    brandName: 'MSI',
    wattage: 160,
    vram: '8GB GDDR6',
    specifications: { 'VRAM': '8GB GDDR6', 'Nguồn': '550W', 'Xung boost': '2565 MHz' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mb-4',
    name: 'Mainboard ASUS TUF GAMING B650-PLUS WIFI (Socket AM5, ATX, DDR5)',
    slug: 'asus-tuf-gaming-b650-plus-wifi',
    sku: 'MB-ASUS-TUF-B650P',
    description: 'Độ bền chuẩn quân sự TUF Alliance, VRM 12+2 pha nguồn tải tốt dòng Ryzen 7 và Ryzen 9.',
    price: 5390000,
    oldPrice: 5990000,
    discount: 10,
    stock: 22,
    soldCount: 65,
    images: ['https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80'],
    rating: 4.85,
    reviewCount: 30,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-mainboard',
    categorySlug: 'mainboard',
    brandId: 'brand-asus',
    brandName: 'ASUS ROG',
    socket: 'AM5',
    ramType: 'DDR5',
    formFactor: 'ATX',
    specifications: { 'Socket': 'AM5', 'RAM': 'DDR5', 'Kích thước': 'ATX' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mb-5',
    name: 'Mainboard MSI PRO B760M-A WIFI DDR4 (LGA1700, Micro-ATX)',
    slug: 'msi-pro-b760m-a-wifi-ddr4',
    sku: 'MB-MSI-PRO-B760M-D4',
    description: 'Bo mạch chủ tiết kiệm chi phí sử dụng RAM DDR4 giá rẻ cho hệ thống Intel Gen 12/13/14.',
    price: 3390000,
    oldPrice: 3890000,
    discount: 13,
    stock: 40,
    soldCount: 155,
    images: ['https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80'],
    rating: 4.7,
    reviewCount: 48,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-mainboard',
    categorySlug: 'mainboard',
    brandId: 'brand-msi',
    brandName: 'MSI',
    socket: 'LGA1700',
    ramType: 'DDR4',
    formFactor: 'Micro-ATX',
    specifications: { 'Socket': 'LGA1700', 'RAM': 'DDR4 (up to 5333MHz OC)', 'Form': 'mATX' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mb-6',
    name: 'Mainboard Gigabyte B550M AORUS ELITE (Socket AM4, Micro-ATX, DDR4)',
    slug: 'gigabyte-b550m-aorus-elite',
    sku: 'MB-GIGA-B550M-ELITE',
    description: 'Lựa chọn số 1 khi dựng cấu hình AMD AM4 tiết kiệm, trang bị 2 khe M.2 và tản nhiệt MOSFET lớn.',
    price: 2490000,
    oldPrice: 2890000,
    discount: 14,
    stock: 35,
    soldCount: 190,
    images: ['https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80'],
    rating: 4.75,
    reviewCount: 62,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-mainboard',
    categorySlug: 'mainboard',
    brandId: 'brand-gigabyte',
    brandName: 'Gigabyte AORUS',
    socket: 'AM4',
    ramType: 'DDR4',
    formFactor: 'Micro-ATX',
    specifications: { 'Socket': 'AM4', 'RAM': 'DDR4', 'Form': 'Micro-ATX' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ram-4',
    name: 'RAM G.Skill Trident Z5 RGB 64GB (2x32GB) DDR5 6400MHz Black',
    slug: 'gskill-trident-z5-rgb-64gb-ddr5-6400mhz',
    sku: 'RAM-GSK-TZ5-64G',
    description: 'Dung lượng khổng lồ 64GB tốc độ cao cho dân dựng đồ họa After Effects, 3D Maya và chạy máy ảo.',
    price: 6890000,
    oldPrice: 7790000,
    discount: 11,
    stock: 14,
    soldCount: 32,
    images: ['https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&auto=format&fit=crop&q=80'],
    rating: 4.95,
    reviewCount: 14,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-ram',
    categorySlug: 'ram',
    brandId: 'brand-corsair',
    brandName: 'Corsair',
    ramType: 'DDR5',
    specifications: { 'Dung lượng': '64GB (2x32GB)', 'Bus': '6400MHz', 'Chuẩn': 'DDR5' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-ssd-3',
    name: 'Ổ Cứng SSD WD Black SN850X 1TB PCIe Gen4 NVMe M.2 2280',
    slug: 'wd-black-sn850x-1tb-pcie-gen4',
    sku: 'SSD-WD-SN850X-1TB',
    description: 'Tốc độ đọc lên tới 7300 MB/s, tính năng Game Mode 2.0 tối ưu tải màn chơi không độ trễ.',
    price: 2690000,
    oldPrice: 3100000,
    discount: 13,
    stock: 35,
    soldCount: 110,
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80'],
    rating: 4.88,
    reviewCount: 42,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-ssd',
    categorySlug: 'ssd',
    brandId: 'brand-samsung',
    brandName: 'Samsung',
    storageType: 'NVMe M.2',
    specifications: { 'Tốc độ đọc': '7300 MB/s', 'Dung lượng': '1TB', 'Bảo hành': '5 năm' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-psu-3',
    name: 'Nguồn Máy Tính ASUS ROG Thor 1000W Platinum II EVA Edition',
    slug: 'asus-rog-thor-1000w-platinum-ii',
    sku: 'PSU-ASUS-THOR-1000W',
    description: 'Nguồn đỉnh cao trang bị màn hình OLED hiển thị công suất tiêu thụ theo thời gian thực và đèn Aura Sync.',
    price: 8990000,
    oldPrice: 9990000,
    discount: 10,
    stock: 6,
    soldCount: 15,
    images: ['https://images.unsplash.com/photo-1587202372583-49330a15584d?w=800&auto=format&fit=crop&q=80'],
    rating: 5.0,
    reviewCount: 9,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-psu',
    categorySlug: 'psu',
    brandId: 'brand-asus',
    brandName: 'ASUS ROG',
    wattage: 1000,
    specifications: { 'Công suất': '1000W', 'Hiệu suất': '80 PLUS Platinum', 'Màn hình': 'OLED Power Display' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-case-2',
    name: 'Vỏ Case Lian Li O11 Dynamic EVO RGB White',
    slug: 'lian-li-o11-dynamic-evo-rgb-white',
    sku: 'CASE-LIANLI-O11D-RGB',
    description: 'Dòng case huyền thoại có thể đảo ngược hướng mở, dải LED RGB viền kép tinh tế trên nền trắng tinh khiết.',
    price: 4690000,
    oldPrice: 5190000,
    discount: 10,
    stock: 12,
    soldCount: 45,
    images: ['https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800&auto=format&fit=crop&q=80'],
    rating: 4.95,
    reviewCount: 28,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-case',
    categorySlug: 'case',
    brandId: 'brand-corsair',
    brandName: 'Corsair',
    formFactor: 'ATX',
    specifications: { 'Form': 'E-ATX/ATX/mATX', 'Chất liệu': 'Nhôm phay xước & Kính cường lực 4mm' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cooler-3',
    name: 'Tản Nhiệt Nước NZXT Kraken Elite 360 RGB LCD White',
    slug: 'nzxt-kraken-elite-360-rgb-lcd-white',
    sku: 'COOL-NZXT-KRAKEN-360',
    description: 'Màn hình LCD 2.36 inch sắc nét 60fps tùy biến ảnh GIF hoặc thông số nhiệt độ thời gian thực.',
    price: 7490000,
    oldPrice: 8200000,
    discount: 9,
    stock: 8,
    soldCount: 24,
    images: ['https://images.unsplash.com/photo-1587202372616-b43abea06c2a?w=800&auto=format&fit=crop&q=80'],
    rating: 4.98,
    reviewCount: 17,
    isFeatured: true,
    isFlashSale: false,
    categoryId: 'cat-cooler',
    categorySlug: 'cooler',
    brandId: 'brand-deepcool',
    brandName: 'DeepCool',
    specifications: { 'Radiator': '360mm', 'Màn hình': '2.36" LCD 640x640', 'Bảo hành': '6 năm' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mon-3',
    name: 'Màn Hình LG UltraGear 27GR95QE-B 27 inch OLED 2K 240Hz 0.03ms',
    slug: 'lg-ultragear-27gr95qe-oled-2k-240hz',
    sku: 'MON-LG-27GR95QE',
    description: 'Màn hình OLED đầu tiên trên thế giới đạt tần số 240Hz thời gian đáp ứng 0.03ms cho độ mượt không đối thủ.',
    price: 19990000,
    oldPrice: 22990000,
    discount: 13,
    stock: 10,
    soldCount: 22,
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80'],
    rating: 4.92,
    reviewCount: 16,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-monitor',
    categorySlug: 'monitor',
    brandId: 'brand-samsung',
    brandName: 'Samsung',
    specifications: { 'Tấm nền': 'OLED', 'Độ phân giải': '2560x1440', 'Tần số': '240Hz' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-gear-3',
    name: 'Chuột Gaming Razer DeathAdder V3 Pro Wireless Ultra-lightweight',
    slug: 'razer-deathadder-v3-pro-wireless',
    sku: 'MOU-RAZ-DAV3-PRO',
    description: 'Thiết kế công thái học hoàn hảo cho tay cầm thuận, trọng lượng 63g, cảm biến Focus Pro 30K quang học.',
    price: 3290000,
    oldPrice: 3890000,
    discount: 15,
    stock: 25,
    soldCount: 88,
    images: ['https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80'],
    rating: 4.88,
    reviewCount: 40,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-gear',
    categorySlug: 'gear',
    brandId: 'brand-razer',
    brandName: 'Razer',
    specifications: { 'Trọng lượng': '63g', 'Cảm biến': 'Focus Pro 30K Optical Sensor' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-gear-4',
    name: 'Bàn Phím Cơ Custom MonsGeek M1 V3 QMK Full Nhôm CNC Gasket Mount',
    slug: 'ban-phim-co-monsgeek-m1-v3-nhom-cnc',
    sku: 'KB-MONS-M1V3',
    description: 'Vỏ nhôm nguyên khối đầm nặng 2kg, cấu trúc Gasket Mount êm ái, hỗ trợ hotswap và phần mềm QMK/VIA.',
    price: 2190000,
    oldPrice: 2590000,
    discount: 15,
    stock: 30,
    soldCount: 115,
    images: ['https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80'],
    rating: 4.9,
    reviewCount: 52,
    isFeatured: false,
    isFlashSale: true,
    categoryId: 'cat-gear',
    categorySlug: 'gear',
    brandId: 'brand-logitech',
    brandName: 'Logitech G',
    specifications: { 'Chất liệu': 'Nhôm CNC 6063', 'Layout': '75%', 'Mạch': 'Hotswap RGB South-facing' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-acc-3',
    name: 'Dây Nguồn Nối Dài ARGB Lian Li Strimer Plus V2 24 Pin Mainboard',
    slug: 'day-nguon-noi-dai-lian-li-strimer-plus-v2-24-pin',
    sku: 'ACC-LIANLI-STRIMER-24P',
    description: 'Dây nguồn phát sáng ARGB rực rỡ biến case PC thành tác phẩm nghệ thuật ánh sáng tương thích L-Connect 3.',
    price: 1390000,
    oldPrice: 1650000,
    discount: 16,
    stock: 35,
    soldCount: 90,
    images: ['https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=800&auto=format&fit=crop&q=80'],
    rating: 4.85,
    reviewCount: 29,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-accessories',
    categorySlug: 'accessories',
    brandId: 'brand-corsair',
    brandName: 'Corsair',
    specifications: { 'Số bóng LED': '120 bóng LED ARGB', 'Độ dày': '8mm siêu dẻo' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-acc-4',
    name: 'Keo Tản Nhiệt Cao Cấp Arctic MX-6 (Tuýp 4g Kèm Thìa Gạt)',
    slug: 'keo-tan-nhiet-arctic-mx-6-4g',
    sku: 'ACC-ARCTIC-MX6-4G',
    description: 'Độ dẫn nhiệt vượt trội, không dẫn điện an toàn tuyệt đối cho CPU và GPU, duy trì hiệu năng tản nhiệt đến 8 năm.',
    price: 190000,
    oldPrice: 240000,
    discount: 21,
    stock: 120,
    soldCount: 550,
    images: ['https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=800&auto=format&fit=crop&q=80'],
    rating: 4.95,
    reviewCount: 230,
    isFeatured: false,
    isFlashSale: false,
    categoryId: 'cat-accessories',
    categorySlug: 'accessories',
    brandId: 'brand-deepcool',
    brandName: 'DeepCool',
    specifications: { 'Độ nhớt': '45000 Poise', 'Thời hạn sử dụng': '8 năm không khô' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }

];

export const initialCoupons: Coupon[] = [
  {
    id: 'coup-1',
    code: 'TECHZONE10',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minOrderValue: 2000000,
    maxDiscount: 1000000,
    usageLimit: 200,
    usedCount: 34,
    isActive: true
  },
  {
    id: 'coup-2',
    code: 'GAMINGPC',
    discountType: 'FIXED',
    discountValue: 500000,
    minOrderValue: 15000000,
    usageLimit: 50,
    usedCount: 12,
    isActive: true
  },
  {
    id: 'coup-3',
    code: 'FREESHIP',
    discountType: 'FIXED',
    discountValue: 30000,
    minOrderValue: 500000,
    usageLimit: 500,
    usedCount: 112,
    isActive: true
  }
];

export const initialOrders: Order[] = [
  {
    id: 'ord-demo-1',
    orderCode: 'TZ-884920',
    userId: 'user-customer-1',
    status: 'DELIVERED',
    paymentMethod: 'BANK_TRANSFER',
    paymentStatus: 'PAID',
    fullName: 'Nguyễn Văn Minh',
    phone: '0987654321',
    email: 'user@techzone.vn',
    address: '123 Đường Nguyễn Huệ, Phường Bến Nghé',
    city: 'Hồ Chí Minh',
    district: 'Quận 1',
    ward: 'Phường Bến Nghé',
    note: 'Giao giờ hành chính giúp mình nhé',
    items: [
      {
        id: 'ord-item-1',
        productId: 'prod-cpu-1',
        name: 'CPU AMD Ryzen 7 7800X3D (4.2GHz Boost 5.0GHz, 8 Nhân 16 Luồng, 104MB Cache, AM5)',
        image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80',
        price: 10490000,
        quantity: 1
      },
      {
        id: 'ord-item-2',
        productId: 'prod-ram-1',
        name: 'RAM Corsair Dominator Titanium RGB 32GB (2x16GB) DDR5 6000MHz White',
        image: 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&auto=format&fit=crop&q=80',
        price: 4690000,
        quantity: 1
      }
    ],
    subtotal: 15180000,
    shippingFee: 0,
    discountAmount: 500000,
    couponCode: 'GAMINGPC',
    total: 14680000,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString()
  },
  {
    id: 'ord-demo-2',
    orderCode: 'TZ-910245',
    userId: 'user-customer-1',
    status: 'SHIPPING',
    paymentMethod: 'COD',
    paymentStatus: 'UNPAID',
    fullName: 'Nguyễn Văn Minh',
    phone: '0987654321',
    email: 'user@techzone.vn',
    address: '123 Đường Nguyễn Huệ, Phường Bến Nghé',
    city: 'Hồ Chí Minh',
    district: 'Quận 1',
    ward: 'Phường Bến Nghé',
    items: [
      {
        id: 'ord-item-3',
        productId: 'prod-gear-1',
        name: 'Chuột Gaming Không Dây Logitech G Pro X Superlight 2 Wireless Black',
        image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80',
        price: 3690000,
        quantity: 1
      }
    ],
    subtotal: 3690000,
    shippingFee: 30000,
    discountAmount: 30000,
    couponCode: 'FREESHIP',
    total: 3690000,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    userId: 'user-customer-1',
    userName: 'Nguyễn Văn Minh',
    userAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    productId: 'prod-cpu-1',
    rating: 5,
    comment: 'Con 7800X3D này bắn Valorant và CS2 FPS cao ngất ngưởng, nhiệt độ chỉ quanh 65-70 độ với tản Deepcool LT720. Đóng gói rất chắc chắn!',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    id: 'rev-2',
    userId: 'user-admin-1',
    userName: 'Chuyên Viên Kỹ Thuật TechZone',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    productId: 'prod-gpu-1',
    rating: 5,
    comment: 'Siêu phẩm RTX 4090 Strix chạy render Blender và kéo màn hình 4K 144Hz quá mượt mà. Đẳng cấp linh kiện cao cấp nhất!',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString()
  }
];
